### PR TITLE
Make the code and tests compatible with 3.8-dev.

### LINKED ISSUE #367: Python 3.8: AttributeError: 'Checker' object has no attribute 'CONSTANT'
pyflakes is completely broken when run against Python 3.8 (not released yet, built from git master):

```console
$ echo 24 | python3.8 -m pyflakes
Traceback (most recent call last):
  File ".../lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ".../lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".../lib/python3.8/site-packages/pyflakes/__main__.py", line 5, in <module>
    main(prog='pyflakes')
  File ".../lib/python3.8/site-packages/pyflakes/api.py", line 203, in main
    warnings = check(sys.stdin.read(), '<stdin>', reporter)
  File ".../lib/python3.8/site-packages/pyflakes/api.py", line 73, in check
    w = checker.Checker(tree, filename)
  File ".../lib/python3.8/site-packages/pyflakes/checker.py", line 533, in __init__
    self.handleChildren(tree)
  File ".../lib/python3.8/site-packages/pyflakes/checker.py", line 881, in handleChildren
    self.handleNode(node, tree)
  File ".../lib/python3.8/site-packages/pyflakes/checker.py", line 928, in handleNode
    handler(node)
  File ".../lib/python3.8/site-packages/pyflakes/checker.py", line 881, in handleChildren
    self.handleNode(node, tree)
  File ".../lib/python3.8/site-packages/pyflakes/checker.py", line 927, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File ".../lib/python3.8/site-packages/pyflakes/checker.py", line 749, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'Checker' object has no attribute 'CONSTANT'
```

Relevant Python bug: https://bugs.python.org/issue32892

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
Closes #367.

### CODE REVIEW

**Comment by joernheissler** [comment]
Works for me, too.

**Comment by sigmavirus24** [comment]
How can we integrate 3.8-dev into our CI so this doesn't regress?

**Comment by joernheissler** [comment]
@sigmavirus24 It looks like "nightly" on Xenial uses 3.8; see https://travis-ci.org/PyCQA/pyflakes/jobs/448803178

**Comment by icemac** [comment]
There is also `3.8-dev` on xenial.

**Comment by joernheissler** [comment]
There is, and it works. But does it make sense to have both `nightly` and a `-dev`?

**Pull request merged**
