### PR TITLE
Add another test for #422

### PR DESCRIPTION
**Pull request by untitaker**
#422

### CODE REVIEW

**Comment by asottile** [comment]
given there's already a test which covers this regression -- is there benefit for two?

**Comment by untitaker** [comment]
idk if this goes through a different codepath or not, feel free to close

**Comment by asottile** [comment]
this is definitely a simpler case of the one I tried to isolate -- in the end it's the same code path though

**Comment by untitaker** [comment]
@asottile do you want me to replace your test or close this?

**Comment by asottile** [comment]
replace is probably good 👍

**Pull request merged**
