### PR TITLE
Add support for PEP 572 assignment expressions

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by jamercee** [comment]
This does not seem to be working.  After installing from master, we receive the following for named-expressions when invoked from flake8::

```
AttributeError: 'FlakesChecker' object has no attribute 'NAMEDEXPR'
"pyflakes" failed during execution due to "'FlakesChecker' object has no attribute 'NAMEDEXPR'"

```

We receive a more verbose error when directly invoking pyflakes::
```

Traceback (most recent call last):
  File "C:\Program Files\Python38\Scripts\pyflakes-script.py", line 11, in <module>
    load_entry_point('pyflakes==2.1.1', 'console_scripts', 'pyflakes')()
  File "C:\Program Files\Python38\lib\site-packages\pyflakes\api.py", line 207, in main
    warnings = checkRecursive(args, reporter)
  File "C:\Program Files\Python38\lib\site-packages\pyflakes\api.py", line 156, in checkRecursive
    warnings += checkPath(sourcePath, reporter)
  File "C:\Program Files\Python38\lib\site-packages\pyflakes\api.py", line 99, in checkPath
    return check(codestr, filename, reporter)
  File "C:\Program Files\Python38\lib\site-packages\pyflakes\api.py", line 74, in check
    w = checker.Checker(tree, file_tokens=file_tokens, filename=filename)
  File "C:\Program Files\Python38\lib\site-packages\pyflakes\checker.py", line 673, in __init__
    self.runDeferred(self._deferredFunctions)
  File "C:\Program Files\Python38\lib\site-packages\pyflakes\checker.py", line 710, in runDeferred
    handler()
  File "C:\Program Files\Python38\lib\site-packages\pyflakes\checker.py", line 1474, in runFunction
    self.handleChildren(node, omit='decorator_list')
  File "C:\Program Files\Python38\lib\site-packages\pyflakes\checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "C:\Program Files\Python38\lib\site-packages\pyflakes\checker.py", line 1120, in handleNode
    handler(node)
  File "C:\Program Files\Python38\lib\site-packages\pyflakes\checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "C:\Program Files\Python38\lib\site-packages\pyflakes\checker.py", line 1120, in handleNode
    handler(node)
  File "C:\Program Files\Python38\lib\site-packages\pyflakes\checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "C:\Program Files\Python38\lib\site-packages\pyflakes\checker.py", line 1119, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "C:\Program Files\Python38\lib\site-packages\pyflakes\checker.py", line 909, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'Checker' object has no attribute 'NAMEDEXPR'
```


Platform:

`Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
`

**Comment by asottile** [comment]
how did you install from `git` -- you'll probably need to do something like `pip uninstall pyflakes` and then `pip install git+https://github.com/pycqa/pyflakes` (pyflakes hasn't bumped the version in `setup.py` so an install from `git` will succeed trivially if `pyflakes` is already installed at version `2.1.1`)

If you show the output from your install command it should say something like "already installed" but if you uninstall and then reinstall it should work!

**Comment by jamercee** [comment]
I hadn't thought to uninstall first. After doing so, works perfectly, thanks.

**Comment by unmade** [comment]
@asottile Is it possible to make a new release with these changes? `pre-commit` with `flake8` hook still installs `pyflakes==2.1.1` which results in a lot of errors for walrus operator.

**Comment by asottile** [comment]
we'll release when we're ready -- even if we were to make a release now it would be pyflakes 2.2.x which is incompatible with the current flake8 release.  flake8 also has some things that need solving before 3.8.x is ready

if you're using pre-commit you can install the current master with something like this:

```yaml
repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        additional_dependencies: [
            '-e', 'git+https://github.com/pycqa/pyflakes@1911c20#egg=pyflakes',
            '-e', 'git+https://github.com/pycqa/pycodestyle@d219c68#egg=pycodestyle',
        ]
```

```python
if x := 1:
    print(x)
```

```console
$ pre-commit run --all-files
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8:-e,-e,git+https://github.com/pycqa/pycodestyle@d219c68#egg=pycodestyle,git+https://github.com/pycqa/pyflakes@1911c20#egg=pyflakes.
[INFO] Installing environment for https://gitlab.com/pycqa/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
flake8...................................................................Passed
```

**Comment by sobolevn** [comment]
I would appreciate a new release! Currently `flake8` is almost useless with code containing `:=`

My setup:

```
flake8.checker            MainProcess   1169 CRITICAL Plugin F raised an unexpected exception
Traceback (most recent call last):
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.8/site-packages/flake8/checker.py", line 435, in run_check
    return plugin["plugin"](**arguments)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.8/site-packages/flake8/plugins/pyflakes.py", line 90, in __init__
    super(FlakesChecker, self).__init__(
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.8/site-packages/pyflakes/checker.py", line 672, in __init__
    self.handleChildren(tree)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.8/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.8/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.8/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.8/site-packages/pyflakes/checker.py", line 1119, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.8/site-packages/pyflakes/checker.py", line 909, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'FlakesChecker' object has no attribute 'NAMEDEXPR'
"pyflakes" failed during execution due to "'FlakesChecker' object has no attribute 'NAMEDEXPR'"
Run flake8 with greater verbosity to see more details
```

Versions:

```
```

**Comment by sobolevn** [comment]
I guess this can be backported to the previous version of `pyflakes`.

**Comment by asottile** [comment]
we haven't really done backports and I don't think this merits the effort necessary for one

**Comment by sobolevn** [comment]
In my experience backports are rather simple:
1. git checkout $PREVIOUS_RELEASE
2. modify the source code
3. new branch, commit, and tag
4. release!
5. merging this branch into master with several conflict fixes

The thing why I am so persuasive on this one is that `flake8` literally throws exceptions at users with `:=`. It is a big bug that can be easily fixed.

**Comment by asottile** [comment]
you can install from git just as easily: https://github.com/PyCQA/pyflakes/pull/457#issuecomment-555714836

**Comment by sobolevn** [comment]
Yes, but it does not solve the problem. When one installs `flake8` or any other tools that depend on `pyflakes` (like `prospector`, etc) this is what happens. 

And after that one has to go to google, find this PR, install correct dependency from git, and then someday remove it when release is ready. 

Why does backport seem like a bad idea to you? Is there anything I can help with?

**Comment by asottile** [comment]
- for one *I* can't release, I don't have pypi permission (I would eventually like to have it, but I haven't asked for it yet)
- pyflakes 2.1.x does not support py38, backporting a fix to make it support it feels not quite right
- the git history gets quite messy with backports (as you've shown above)
- this isn't a show stopping bug, it's the inability to use a new syntax feature
- the precedent is not in favor of doing so: for example we didn't backport f-strings to older pyflakes versions (despite that being _wayyy_ more popular than assignment expressions)
- I think it would be preferable to make 2.2 (and probably start with 2.2.0a1 since there's been quite churn since 2.1)

**Comment by asottile** [comment]
and note that for the future, #490 makes this sort of squabble much less necessary

**Comment by sobolevn** [comment]
Fair enough! Thanks a lot for the detailed answer 👍

**Comment by asmeurer** [comment]
What would be the point of backporting? Are you unable to upgrade to the latest version for some other reason?

**Pull request merged**
