### PR TITLE
namespace pyflakes's node monkeypatches

### PR DESCRIPTION
**Pull request by asottile**
See https://gitlab.com/pycqa/flake8/issues/536 for full explanation

Basically bandit *also* monkeypatches `astnode.parent` which confuses `pyflakes`.  This manifests when running both of the tools as plugins inside of flake8.

### CODE REVIEW

**Comment by sobolevn** [comment]
@asottile thanks for reporting https://github.com/wemake-services/wemake-python-styleguide/issues/519

This is a braking change, since I am absolutely sure that a lot of plugin-developers rely on `.parent` property. Just to mention.

**Comment by asottile** [comment]
> @asottile thanks for reporting [wemake-services/wemake-python-styleguide#519](https://github.com/wemake-services/wemake-python-styleguide/issues/519)
> 
> This is a braking change, since I am absolutely sure that a lot of plugin-developers rely on `.parent` property. Just to mention.

I would hope things aren't depending on the side effects of pyflakes?

**Comment by asottile** [comment]
> > @asottile thanks for reporting [wemake-services/wemake-python-styleguide#519](https://github.com/wemake-services/wemake-python-styleguide/issues/519)
> > This is a braking change, since I am absolutely sure that a lot of plugin-developers rely on `.parent` property. Just to mention.
> 
> I would hope things aren't depending on the side effects of pyflakes?

Also note this is **pyflakes** not flake8

**Comment by sobolevn** [comment]
@asottile I am pretty sure they do 🙂 
I have even seen this inside some `flake8`'s plugins source code.

**Comment by asottile** [comment]
> @asottile I am pretty sure they do 
> I have even seen this inside some `flake8`'s plugins source code.

They wouldn't work 50% of the time due to plugin ordering.

**Comment by sobolevn** [comment]
@asottile friendly ping. 

(asking maintainers) Is this going to be merged anytime soon? I rely on this change 🙂

**Comment by asottile** [comment]
I don't believe there's anything left for me to do here, I believe this to be mergeable and the fear above to be false

**Comment by sobolevn** [comment]
@myint so, what else do we need to get this merged and released? 🙂 
I am pushing this, since my users face this bug quite frequently.

**Comment by myint** [comment]
The convention in this repositories is to have two reviewers approve of the pull request. Currently, I'm the only one that has reviewed it. This is just waiting for a second reviewer.

**Comment by asottile** [comment]
> The convention in this repositories is to have two reviewers review the code and approve of the pull request. Currently, I'm the only one that has reviewed it. This is just waiting for a second reviewer.

oh wow, I didn't even notice -- are there enough active maintainers for dual sign-off?

**Comment by myint** [comment]
Hmm, that was the convention when we set this repository up long ago. I was busy for a *quite* while and then came back to review things. Did my fellow maintainers go away to take a break in time? 😛

**Comment by myint** [comment]
I don't have admin access, but can someone make @asottile one of the maintainers? Most of the commits in recent history are from him.

**Comment by ulziibay** [comment]
Hello, running into this issue. Has this been released? It looks like it has not as https://pypi.org/project/pyflakes/2.1.1/ predates this. What is the recommended steps to workaround this?

**Comment by sobolevn** [comment]
I guess not 🙁

**Comment by asottile** [comment]
It [has not yet](https://github.com/PyCQA/pyflakes/issues/494#issuecomment-561303887) -- if you upgrade the other conflicting package (I believe it was bandit?) it should resolve

**Comment by ulziibay** [comment]
Upgrading to bandit `1.6.2` does not solve the problem for me. Also, I am not sure why having pyflakes 2.1.1 and bandit causes this issue. The stack trace seems to indicate its entirely pyflakes issue. This is my flake8 setup btw: 
```
{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.7.2",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "click-best-practices",
      "version": "0.1.0"
    },
    {
      "is_local": false,
      "plugin": "click-launch-uses-literal",
      "version": "0.1.0"
    },
    {
      "is_local": false,
      "plugin": "click-option-check",
      "version": "0.1.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-flask",
      "version": "0.6.0"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.1.1"
    }
  ],
  "version": "3.7.9"
}
```

**Comment by asottile** [comment]
ah you don't even have bandit, it must be one of click-best-practices, click-launch-uses-literal, click-option-check, or flake8-flask

I can't find the source for click-launch-uses-literal or click-option-check but suspect those two (the others look fine)

**Comment by ulziibay** [comment]
@asottile ok thanks

**Comment by asottile** [comment]
but basically, two plugins are monkeypatching `.parent` in different ways causing a conflict

**Pull request merged**
