### PR TITLE
Improve @overload detection

### LINKED ISSUE #434: F811 (redefinition of unused variable) incorrectly triggered with @overload decorator
This bug was fixed for functions in #320. It still occurs if the function is inside a class and/or has multiple decorators (e.g. @staticmethod, @classmethod):
```python
from typing import overload


class test:
    @overload
    def utf8(value: None) -> None:
        pass

    @overload
    def utf8(value: bytes) -> bytes:
        pass

    @overload
    def utf8(value: str) -> bytes:
        pass

    def utf8(value):
        pass  # actual implementation
```

```
test.py:9:5: F811 redefinition of unused 'utf8' from line 5
test.py:13:5: F811 redefinition of unused 'utf8' from line 9
test.py:17:5: F811 redefinition of unused 'utf8' from line 13
```

```python
from typing import overload


def do_nothing(func):
    return func


@overload
@do_nothing
def utf8(value: None) -> None:
    pass


@overload
@do_nothing
def utf8(value: bytes) -> bytes:
    pass


@overload
@do_nothing
def utf8(value: str) -> bytes:
    pass


def utf8(value):
    pass  # actual implementation
```

```
test.py:14:1: F811 redefinition of unused 'utf8' from line 8
test.py:20:1: F811 redefinition of unused 'utf8' from line 14
test.py:26:1: F811 redefinition of unused 'utf8' from line 20
```

### PR DESCRIPTION
**Pull request by asottile**
Resolves #434

### CODE REVIEW

**Comment by Zac-HD** [comment]
Hurray!  

This fixes another bug too: in the current released version, using a decorator named `overload` causes an internal error (because pyflakes thinks that it's `typing.overload`, and tries to access a nonexistent scope name).  We first noticed this a while ago in [Hypothesis' build](https://travis-ci.org/HypothesisWorks/hypothesis/jobs/498740860#L783), but it's reproducible by running `pyflakes` on the following file:

```python
overload = lambda f: f  # or `def overload(arg): return arg

@overload
def func(arg): pass

def func(arg): return ...
```

Happily I've confirmed that this change fixes pyflakes for both the minimal case above (which might be worth adding as another test case for this PR?) and for Hypothesis - thanks @asottile 😍

**Comment by asottile** [comment]
@Zac-HD 🎉 though it was probably #423 that fixed that one ~o/

**Comment by Zac-HD** [comment]
Yeah, probably... still fixed though and still fixed by you 😁

**Comment by asottile** [comment]
heh only fair -- I broke it in the first place /o\

**Comment by kelseyfrancis** [comment]
Thanks for fixing this! Could you all please cut a pypi release that includes this fix?

**Comment by omry** [comment]
When is this expected to make it to flake8?

**Comment by asottile** [comment]
no current plan, but you can read my thoughts [here](https://github.com/PyCQA/pyflakes/issues/494#issuecomment-561303887) or as a temporary workaround install from `git+https://github.com/pycqa/pyflakes@revision_here`

**Comment by omry** [comment]
Looks like this issue still happens with master on python 3.8.

**Comment by asottile** [comment]
doesn't happen for me?  try uninstalling `pyflakes` before installing from `git` (I suspect you're not using the actual git install)

**Comment by omry** [comment]
You are right, I had a system wide flake8 installed and bash already had it cached as flake8.

**Comment by omry** [comment]
@ asottile, unfortunately depending on a git version in setup.py prevents publishing a package.
would you be able to make a dev/pre release?

**Comment by asottile** [comment]
it's a bit unusual to depend on pyflakes in `setup.py` -- could you elaborate on the usecase?

(I also don't have pypi permission, I believe @bitglue manages that)

**Comment by omry** [comment]
Sure:
I am depending on flake for linting my code [here](https://github.com/omry/omegaconf/blob/11dd822e5ca0265216896cb6ccd5c7d451544146/setup.py).

Because of this overload bug, I am also depending on pyflake to get this bugfix.
This dependency (as well as the one with isort which is due to a similar problem) are preventing me from publishing the package as is (and I need to hack those out before publishing).

**Comment by asottile** [comment]
ah I see -- those dependencies aren't for your consumers so there isn't really a need to put them in `setup.py` -- maybe put them in your `nox` file instead?

**Comment by omry** [comment]
developers are also consumers.
I am using "pip install -e .[dev]" to setup the development environment.

my noxfile is also [settings up](https://github.com/omry/omegaconf/blob/11dd822e5ca0265216896cb6ccd5c7d451544146/noxfile.py#L48) in the same way.

**Comment by asottile** [comment]
yeah I notice you're using pre-commit -- I'm the author (you've got it set up in a less-than-supported manner -- first you don't need `.pre-commit-hooks.yaml` that's for _providing_ hooks, next you're using the escape hatch `local` + `system` hooks instead of versioning directly in `.pre-commit-config.yaml`) -- but that's a separate discussion entirely :)

when I said consumers above, I meant people that would install your package -- I understand you still want to have a developer workflow, I'm just suggesting that while `setup.py` does work for that, it isn't really the intended mechanism (whereas something more for your developer workflow such as `nox` / `tox` / `poetry` or even `requirements-dev.txt` is more properly suited for that)

**Comment by omry** [comment]
Thanks for the pointers! didn't realize you are the author of pre-commit hooks.
About that, I was following the instructions from Black, I was a bit confused about the purpose of the second file.
Looking now, looks like Black got [better instructions](https://black.readthedocs.io/en/stable/version_control_integration.html). I update and clean up the mess.

**Comment by omry** [comment]
I [fixed](https://github.com/omry/omegaconf/blob/87d903d80d4cac6ae209d26f18004f99833b0912/.pre-commit-config.yaml) the pre-commit config for black to not use the local escape hatch, but I am not sure how to do it for flake8 given the need to install a specific revision of pyflakes.

**Comment by asottile** [comment]
something like this:

```yaml
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        additional_dependencies: [-e, git+https://github.com/pycqa/pyflakes@...]
```

**Comment by omry** [comment]
Awesome, thanks!

**Pull request merged**
