### PR TITLE
Don't warn about unused `_` magic var

### LINKED ISSUE #202: Ignore "_" vars in "Unused Variable" check
*Original report by [archardlias](https://launchpad.net/~archardlias) on [Launchpad](https://bugs.launchpad.net/bugs/1328169):*

------------------------------------

Would it be possible to ignore variables named "_" from "Unused Variable" checks?

I'm not really sure whether "_" is officially specified anywhere. But I do see it a lot and in a lot of languages including python to denote a variable to be ignored (place holder dummy). PyLint implements this pseudo(?)-convention (? second-hand knowledge).

Would be great, since I would love to be explicit about "things returned but not used" instead of just calling without assignment which looks tantamount to "this function does never return anything / does not contain a return statement". A great plus in signature visibility throughout the code, specially for first-time readers.

Best regards,
~arlias

### PR DESCRIPTION
**Pull request by krader1961**
Resolves #202

### CODE REVIEW

**Comment by krader1961** [comment]
This is derived from PR #335. That PR prematurely expanded the scope to all vars with a leading underscore. This variant limits it to just the magic `_` var. It is a shame that @smontanaro couldn't set aside their belief that all vars with a leading underscore should be exempt from this check so that they would get credit for the improvement that resolves issue #202.

**Comment by smontanaro** [comment]
Note that I added a comment about the docstring in the new test function.

**Comment by jayvdb** [comment]
While not strictly relevant to your patch, it would be useful to add a test here to ensure that `_` import is not ignored.

```
    def test_unusedImport_underscore(self):
        self.flakes('import fu as _', m.UnusedImport)
```

With all the `_` special cases happening, I worry that one will become ignored also.

**Comment by krader1961** [comment]
I had forgotten I even opened this it's so old. I also see my unit test comment is bogus because I copied it from the flawed PR #334.

```
Don't warn when an unused variable starts with an underscore.
```

That should say something like "Don't warn when the unused variable is the magic underscore var."

@jayvdb Do you want to just merge this and fix the issues yourself or wait for me to muster the energy to address you comment and my observation about the added unit test?

**Comment by jayvdb** [comment]
Oh, I missed that :)

It needs to be rebased and docstring fixed before merging.
We can do that for you, if necessary.

**Comment by krader1961** [comment]
@jayvdb I rebased, fixed the doc string, and added your import test case. I also verified via selective mutation that the import test case is definitely not affected by this change.

**Comment by jayvdb** [comment]
Thanks @krader1961.

**Comment by g4borg** [comment]
disappointing there is no way with this patch to extend it to all _variables, as in majority of django or Qt python projects, _ gets assigned to gettext, so using _x or similar is indeed quite common, and imho more pythonic, verbose, smarter and well behaved practice

it is also already picked up by code analyzers, e.g. pydev on eclipse by default ignores _vars in the local scope.

this way this warning is more likely to be ignored completely.

it should almost be a separate warning code for variables with _, that would be a much more flexible solution.

**Pull request merged**
